!function(){
    var body = document.getElementsByTagName("body")[0];
    var header = document.createElement("div");
    header.innerHTML  = '<header>'
                +    '<div class="lay-top-menu-con">'
                +        '<div class="lay-content clear">'
                +            '<img class="lay-logo" src="images/logo.png" alt="">'
                +            '<ul class="lay-menu clear">'
                +                '<li><a href="javascript:;">时尚女装</a></li>'
                +                '<li><a href="javascript:;">精品男装</a></li>'
                +                '<li><a href="javascript:;">3C数码</a></li>'
                +                '<li><a href="javascript:;">汽车周边</a></li>'
                +            '</ul>'
                +            '<ul class="lay-icon-menu clear dat-icon-menu">'
                +                '<li class="icon iconfont icon-sousuo dat-icon-menu-btn"></li>'
                +                '<li class="icon iconfont icon-yonghu dat-icon-menu-btn"></li>'
                +                '<li class="icon iconfont icon-gouwuche"></li>'
                +                '<li class="icon iconfont icon-caidan"></li>'
                +            '</ul>'
                +        '</div>'
                +    '</div>'
                +'</header>'
                +'<ul class="lay-back-menu dat-back-menu hide">'
                +    '<li class="hide">'
                +        '<div class="lay-search clear">'
                +            '<input class="lay-search-input dat-search-input" type="search" palceholder="冬装">'
                +            '<input class="lay-search-button" type="button">'
                +        '</div>'
                +    '</li>'
                +    '<li class="hide">'
                +        '<div class="lay-sign">'
                +            '<label for="dat-account">账号：<input id="dat-account" type="text" placeholder="请输入账号"></label>'
                +            '<label for="dat-password">密码：<input id="dat-password" type="text" placeholder="请输入密码"></label>'
                +            '<input class="lay-sign-btn" type="button" value="登录">'
                +            '<p class="lay-register"><a>注册</a>|<a>找回密码</a></p>'
                +        '</div>'
                +    '</li>'
                +'</ul>';
    body.insertBefore(header,body.firstElementChild);
}();